### ISSUE TITLE
Text not rendering on the wheel for iOS

### ISSUE THREAD

**Issue by Apetrou** [eftalyurtseven/react-native-wheel-of-fortune#12]
Hi there,

Is anyone else having issues whereby the wheel is not rendering any text or images on iOS?
Android seems to be fine.

Thanks @eftalyurtseven  for this package btw it's great!

Alkis.

**Comment by eftalyurtseven** [comment]
Hello @Apetrou thank you for your comment.
I think the reason why the articles do not appear is related to "position" or "style". I am aware that I have made this repo and will continue to develop it at my first available time.

**Comment by Apetrou** [comment]
Thanks for the quick response @eftalyurtseven !
In that case, I will have a play around with the styling and see if I can get it working.

**Comment by kukuandroid** [comment]
@Apetrou  found the solution ?

**Comment by burakozturk16** [comment]
The solution is which I find; Change iterated value from  in _textRender function;

before: length: value.length
after   : length: value.toString().length

**Comment by kukuandroid** [comment]
@burakozturk16  Thankss mateee
