### ISSUE TITLE
Çarkı 2.kez dödüremiyorum.Ve çark üzerinde sayılar gözükmüyor.Kod aşağıda

### ISSUE THREAD

**Issue by Ekremalpozmen** [eftalyurtseven/react-native-wheel-of-fortune#14]
import React, { Component } from "react";
import {
  View,
  Text,
  StyleSheet,
  StatusBar,
  Button
} from "react-native";

import WheelOfFortune from 'react-native-wheel-of-fortune';

const rewards = [1,2,3,4,5,6,7,8,9,10]

class App extends Component {

  constructor(props) {
    super(props);

    this.state = {
      winnerValue: null,
      winnerIndex: null
    }
    this.child = null
  }

  _renderPlayButton = () => {
    return (
      <Text style={styles.tapToStart}>TAP TO PLAY</Text>
    );
  }

  render() {
    return (
      <View style={styles.container}>
        <StatusBar barStyle={'light-content'} />
        <WheelOfFortune
    onRef={ref => (this.child = ref)} 
    rewards={ rewards }
    knobSize={20}
    borderWidth={3}
    borderColor={"#FFF"}
    winner={3}
    innerRadius={50}
    backgroundColor={"#c0392b"}
    getWinner={(value, index) => this.setState({ winnerValue: value, winnerIndex: index })}
/>
<Button title="Press me" onPress={ () => { this.child._onPress() } } />
       
      </View>
    );
  }
}
export default App;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'aquamarine'
  },
  winner: {
    width: '100%',
    position: 'absolute',
    padding: 10,
    backgroundColor: 'black',
    bottom: 50,
    justifyContent: 'center',
    alignItems: 'center'
  },
  winnerText: {
    fontSize: 26,
    color: 'black'
  },
  tapToStart: {
    fontSize: 50,
    color: '#fff',
    fontWeight: 'bold'
  }
});

**Comment by gundogduyakici** [comment]
Sayılar bende de gözükmüyor fakat 2. kez döndürmek için this.child içerisini tekrar null set etmeyi deneyin

**Comment by eftalyurtseven** [comment]
please upgrade to new version
