### ISSUE TITLE
Replace each section by images

### ISSUE THREAD

**Issue by Jim25** [eftalyurtseven/react-native-wheel-of-fortune#15]
Hi,

This is great library, but how can I replace each section in the circle by images. I want to use different images for each sections not just color and numbers.

Thank you in advance.

**Comment by MGR87** [comment]
Hi, I have also the same idea. let me know what solution you have. Thanks

**Comment by Jim25** [comment]
@MGR87 if you are still interested in the solution, email me.
Thanks.

**Comment by sanja-dev** [comment]
Hi, do you have any solution for it?

**Comment by eftalyurtseven** [comment]
I'm added to-do list.

**Comment by nvphi91** [comment]
that is great idea, i hope ad will do it

**Comment by bouchja1** [comment]
Hi guys, @Jim25 and @MGR87. Did you solve it somehow? If so, do you have any code snippet how to do it? Thanks.

**Comment by Jim25** [comment]
Hi,
Yes, I did it. Just change text to image and pass an image array to it.

Regards,

Vào Th 4, 8 thg 9, 2021 vào lúc 15:05 Jan Bouchner <
***@***.***> đã viết:

**Comment by kukuandroid** [comment]
@Jim25  Hi, can you give code example ? Thank you
