### ISSUE TITLE
winner={0} showing random winners

### ISSUE THREAD

**Issue by arunkarnann** [eftalyurtseven/react-native-wheel-of-fortune#18]
winner={0} showing random winners, means delaring first element of the array always returns random results

**Comment by rafikhdj** [comment]
Yes because, in his class of the Wheel, you can choose between your choice and a random choice
this.winner = {this.winner ? this.winner : radom(winner) }
so when you set winner to 0 it means equal to false as :
{false ? this.winner : radom(winner) } => radom(winner)
