### ISSUE TITLE
Error while using the library: require('../assets/images/knob.png')

### ISSUE THREAD

**Issue by alexandruionascu** [eftalyurtseven/react-native-wheel-of-fortune#19]
I think the knob asset is no longer in the folder, no matter if you specify the knobSource or not, the require seem to fail.

**Comment by thomas-cruz** [comment]
I'm getting this error too. I haven't found any work arounds unfortunately

**Comment by alexandruionascu** [comment]
The workaround I found is to create a local copy of the module and change that asset.
The library is great, but I suggest some additional fixes, like this one, and also some responsiveness would be great.

**Comment by fergusonjason** [comment]
I'm getting the same error.

**Comment by ownsupernoob2** [comment]
Hello, sorry for the late response. The Author way of answering it was confusing so here you go. Go to `node_modules` then to `react-native-wheel-of-fortune` go to folder `assets` then `images` then add this [https://raw.githubusercontent.com/gdambrosio132/WheelofMoney/8c22bd13aaaa7ce21104f07ff80907c1432bd86a/app/assets/knob.png](image)  and there you good to go.
