### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by ownsupernoob2** [eftalyurtseven/react-native-wheel-of-fortune#20]
So when downloading the package I got two errors the first one was no problem but they should also fix that which is `there no image called 'knob.png'`  the second error I struggled with:

`undefined is not an object (evaluating'_this.props.options.reward)`

and I have no idea how to fix it. Any help?

**Comment by kilimchoi** [comment]
you need to change `<WheelOfFortune wheelOptions={wheelOptions} />` to `<WheelOfFortune options={wheelOptions} />`

**Comment by ownsupernoob2** [comment]
Thanks! it worked.
