### ISSUE TITLE
More Information? and RewardList ?

### ISSUE THREAD

**Issue by HeinXtet** [eftalyurtseven/react-native-wheel-of-fortune#3]
rewards value is only show in string array. not showing int array .
const rewards = ["a", "b","c", "d","d"]

and how to reset wheel when finish one wheel to find winner ?

**Comment by eftalyurtseven** [comment]
Yep, rewards value must be string array. 
You should use **getWinner** callback function. This return 2 parameters: _winnerValue,winnerIndex_ 
No reset function yet, I've added it to the to-do list in the new version.
