### ISSUE TITLE
Android - different behaviour when the React Native Debugger is not working

### ISSUE THREAD

**Issue by EmreDereli** [eftalyurtseven/react-native-wheel-of-fortune#31]
It works well on ios devices but it is **not** working **when the React Native Debugger is not working** I attached the screenshots. You can find the rotation of each slice. When I checked the logs, the **_wheelPaths** lists are the same.  How can I fix this error ?

**Debug mode off :** 

![Ekran Resmi 2021-11-09 12 34 41](https://user-images.githubusercontent.com/24767365/141084802-89d35ed9-c12e-40e3-89d6-068f971a7c34.png)

**Debug mode on :** (expected behaviour)

![Ekran Resmi 2021-11-09 12 36 49](https://user-images.githubusercontent.com/24767365/141084889-5de5b800-090e-4e94-a0cd-00a4b6989e55.png)

**Comment by NooruddinLakhani** [comment]
Getting the same issue and working fine when debugger on, any solution?

**Comment by EmreDereli** [comment]
> Getting the same issue and working fine when debug mode on, any solution?

Yes in debug mode it changes the order by itself. So you need to order your list by angle

**Comment by NooruddinLakhani** [comment]
@EmreDereli  Thanks, I will try the solution
