### ISSUE TITLE
"export 'default' (imported as 'WheelOfFortune') was not found in 'react-native-wheel-of-fortune'

### ISSUE THREAD

**Issue by grace-nm** [eftalyurtseven/react-native-wheel-of-fortune#37]
Unsure of how to fix this. Google has not helped.

The index file of WheelOfFortune definitely explicitly states its export default.

**Comment by thecogmel** [comment]
me too

**Comment by grace-nm** [comment]
@thecogmel I found the solution is to not run it using npm yarn web or expo -w or whatever - because the error is something to do with the web version not working.
best to run on xcode ios or android simulator -> then there is no run time error and it works.
