### ISSUE TITLE
Unable to see reward text on wheel

### ISSUE THREAD

**Issue by masineedi** [eftalyurtseven/react-native-wheel-of-fortune#4]
![Screenshot 2019-10-20 at 12 04 04 AM](https://user-images.githubusercontent.com/31059206/67149795-3735c900-f2cd-11e9-81ac-086b21d22410.png)
HI I have installed but unable see the reward text

**Comment by eftalyurtseven** [comment]
Can you share your code please?
you can use **getWinner** callback property like this
` getWinner={(value, index) => console.log("Winner Value: " + value + " , Winner Index: " + index)}`

**Comment by masineedi** [comment]
inside the wheel no text

**Comment by masineedi** [comment]
this is my JSON how can connect this
 "luckycolor": [
        {
            "id": 1,
            "colorname": "Colour: Cru00e8me.",
            "colorcode": "#ffffff"
        },
        {
            "id": 2,
            "colorname": "Colour: Bergandi Red.",
            "colorcode": "#ffffff"
        },
        {
            "id": 3,
            "colorname": "Colour: Light grey.",
            "colorcode": "#ffffff"
        },
]

**Comment by eftalyurtseven** [comment]
You can not connect this format. 
You should create an array for rewards. Please detailed review Readme.md and /Example folder.

**Comment by masineedi** [comment]
Is it possible to Display text inside the wheel parts

**Comment by masineedi** [comment]
Iam unable to see the inside wheel pieces

**Comment by tmdeginal** [comment]
This issue was not solved

**Comment by rschneid0** [comment]
rewards prop expects a list of strings. try ` let rewards = ["1", "2"] ` to see what I mean

**Comment by tmdeginal** [comment]
Iam adding text in reawards it is taking latter spacing

**Comment by tmdeginal** [comment]
Now it is working fine

**Comment by sreenu74** [comment]
We can add text and it is displaying on each slice of the wheel properly, but text aligned vertically not horizontally.
How do we align text horizontally?

Thanks.

**Comment by burakozturk16** [comment]
The solution is which I find; Change iterated value from  in _textRender function;

before: length: value.length
after   : length: value.toString().length
