### ISSUE TITLE
Tspan is Taking more space for I letter

### ISSUE THREAD

**Issue by tmdeginal** [eftalyurtseven/react-native-wheel-of-fortune#5]
![Screenshot 2019-12-03 at 10 11 46 AM](https://user-images.githubusercontent.com/11443303/70021136-9a499980-15b5-11ea-823c-ede6ff9b6c31.png)

I am trying to do some customization text in the wheel but in the text I letter is taking more space can you help me for this

**Comment by eftalyurtseven** [comment]
Please share your code file
