### ISSUE TITLE
Labels on cards are not showing up

### ISSUE THREAD

**Issue by greulist137** [eftalyurtseven/react-native-wheel-of-fortune#6]
Hi All,

I copied and pasted the code and it is not showing the labels on the spinner. I just see the colors.
![Simulator Screen Shot - iPhone X - 2019-12-11 at 17 09 51](https://user-images.githubusercontent.com/19229760/70664827-38360780-1c39-11ea-9f27-aad62003d3c2.png)

**Comment by greulist137** [comment]
Nevermind, was able to pull off the non-master and got it to work!

**Comment by burakozturk16** [comment]
The solution is which I find; Change iterated value from  in _textRender function;

before: length: value.length
after   : length: value.toString().length
