### ISSUE TITLE
TypeError: _this.props.onRef is not a function

### ISSUE THREAD

**Issue by greulist137** [eftalyurtseven/react-native-wheel-of-fortune#7]
Hi,

I keep getting an eror for: TypeError: _this.props.onRef is not a function

I did a fresh react native project and installed the latest packages of SVG and D3 and receive this error.  

index.bundle?platfor…&minify=false:28837 Unhandled JS Exception: TypeError: _this.props.onRef is not a function

This error is located at:
    in WheelOfFortune (at App.js:69)
    in RCTView (at App.js:68)
    in RCTView (at App.js:66)
    in App (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

**Comment by eftalyurtseven** [comment]
Please share your code

**Comment by receppolat** [comment]
if you are using func comp u should change onRef like this 
`onRef: ref => (refWheel.current = ref), `
