### ISSUE TITLE
I need to align text horizontally not Vertically, for this I need to change index.js file in the src folder

### ISSUE THREAD

**Issue by sreenu74** [eftalyurtseven/react-native-wheel-of-fortune#8]
I need to align text horizontally not Vertically on each slice of a wheel, for this I need to change index.js file in the src folder. but we should not modify index.js right, then how do I change alignment without modifying index.js file(have more things need to change in index.js), Please clarify me?

**Comment by eftalyurtseven** [comment]
Its not possible this version. I'm update as soon as possible.
